import { test, expect } from '@playwright/test'

function nextWorkingDay() {
  const d = new Date(); d.setUTCDate(d.getUTCDate() + 3)
  if (d.getUTCDay() === 0) d.setUTCDate(d.getUTCDate() + 1)
  return d.toISOString().slice(0, 10)
}

test('cadastro, pet, reserva e cancelamento pelo tutor', async ({ page }) => {
  await page.goto('/entrar')
  await page.getByRole('button', { name: 'Cadastre-se', exact: true }).click()
  await page.getByLabel('Seu nome').fill('Lucas Teste')
  await page.getByLabel('E-mail', { exact: true }).fill(`e2e${Date.now()}@example.com`)
  await page.getByLabel('Senha', { exact: true }).fill('PetStyle123!')
  await page.getByRole('button', { name: 'Criar minha conta' }).click()
  await expect(page.getByRole('heading', { name: 'Olá, Lucas.' })).toBeVisible()
  await page.getByRole('button', { name: 'Cadastrar pet', exact: true }).click()
  await page.getByLabel('Nome do pet').fill('Fubá')
  await page.getByRole('button', { name: 'Salvar pet' }).click()
  await expect(page.getByRole('heading', { name: 'Fubá', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Novo agendamento', exact: true }).click()
  await page.getByRole('button', { name: 'Escolher horário' }).click()
  await page.getByLabel('Data do atendimento').fill(nextWorkingDay())
  await page.locator('.slot-btn').first().click()
  await page.getByRole('button', { name: 'Revisar reserva' }).click()
  await page.getByRole('button', { name: 'Confirmar agendamento' }).click()
  await expect(page.getByRole('heading', { name: 'Está marcado!' })).toBeVisible()
  await page.getByRole('link', { name: 'Ver meus agendamentos' }).click()
  await expect(page.getByText('Confirmado', { exact: true })).toBeVisible()
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await expect(page.getByText('Cancelado', { exact: true })).toBeVisible()
})

test('equipe altera disponibilidade e cadastra serviço', async ({ page }) => {
  await page.goto('/entrar')
  await page.getByRole('button', { name: 'Demo: equipe' }).click()
  await expect(page.getByRole('heading', { name: 'Painel da equipe' })).toBeVisible()
  await page.getByRole('button', { name: 'Disponibilidade', exact: true }).click()
  await page.getByLabel('Consultar dia').fill(nextWorkingDay())
  const block = page.getByRole('button', { name: /^Bloquear/ }).first()
  await expect(block).toBeEnabled()
  const time = (await block.getAttribute('aria-label')).replace('Bloquear ', '')
  await block.click()
  const unlock = page.getByRole('button', { name: `Liberar ${time}`, exact: true })
  await expect(unlock).toBeEnabled()
  await unlock.click()
  await expect(page.getByRole('button', { name: `Bloquear ${time}`, exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Serviços', exact: true }).click()
  await page.getByLabel('Nome', { exact: true }).fill(`Cuidado E2E ${Date.now()}`)
  await page.getByLabel('Descrição', { exact: true }).fill('Serviço criado no teste de navegação.')
  await page.getByLabel('Preço em reais').fill('95,50')
  await page.getByRole('button', { name: 'Salvar serviço' }).click()
  await expect(page.getByText('Serviço salvo.', { exact: false })).toBeVisible()
})

test('menu e conteúdo cabem em tela de celular', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('h1')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: /menu/i }).click()
  await page.getByRole('link', { name: /entrar/i }).first().click()
  await expect(page.getByLabel('E-mail', { exact: true })).toBeVisible()
})
